#!/bin/bash
# Copyright (c) 2007 Alon Swartz - all rights reserved
#
# Add in the bzr branches in the branches file.
# All braches will be stored in the "bzr" folder (will be created).
# If the branch already exists, only the latest changes will be pulled.

. branches

BASE=`pwd`

for branch in ${BRANCHES[*]}; do
	name=`basename $branch`
	bzrdir=$BASE/bzr/$name
	if [ -d $bzrdir ]; then
		echo "Checking for updates in: $name"
		cd $bzrdir
		bzr pull $branch
	else
		echo "Getting new branch: $name"
		mkdir -p $BASE/bzr
		cd $BASE/bzr
		bzr branch $branch $name
	fi
	echo
done

