#!/bin/sh

PREREQ=""
DESCRIPTION="Configuring fstab..."
FSTAB=/root/etc/fstab

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

grep -q "UNCONFIGURED FSTAB" $FSTAB && (cat > $FSTAB <<EOF)
aufs / aufs rw 0 0
tmpfs /tmp tmpfs nosuid,nodev 0 0
EOF

#rm -f /root/etc/rcS.d/S*checkroot.sh

log_end_msg
