#!/bin/sh
#Eject CD if system is loaded into ram
NAME=eject-if-toram

set -e
. /lib/lsb/init-functions

#Exit if system was not booted by casper
grep -qs boot=casper /proc/cmdline || exit 0

case "$1" in
  start)
    log_begin_msg "Starting $NAME"
    if livestate bootmedia=cdr && livestate rootfs=ram; then
        eject &
    fi
    log_action_end_msg $?
  ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        # No-op
        ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start}" >&2
    exit 1
  ;;
esac

exit 0
